spring:
  r2dbc:
    url: r2dbc:h2:mem:///ECOMMERCE?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: root
    initialization-mode: always
    pool:
      max-size: 10
      max-create-connection-time: 10s