-- DROP SEQUENCE public.companies_id_seq;

CREATE SEQUENCE public.companies_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.company_tax_addresses_id_seq;

CREATE SEQUENCE public.company_tax_addresses_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.customer_tax_addresses_id_seq;

CREATE SEQUENCE public.customer_tax_addresses_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.roles_id_seq;

CREATE SEQUENCE public.roles_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.user_id_seq;

CREATE SEQUENCE public.user_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public.company_tax_addresses definition

-- Drop table

-- DROP TABLE public.company_tax_addresses;

CREATE TABLE public.company_tax_addresses (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	company int4 NOT NULL,
	country int4 NOT NULL,
	province_state int4 NOT NULL,
	zip_code varchar(15) NOT NULL,
	city varchar(50) NOT NULL,
	street varchar(100) NOT NULL,
	"number" varchar(10) NULL,
	created_date timestamp NOT NULL DEFAULT now(),
	created_user varchar(10) NOT NULL,
	updated_user varchar(10) NULL,
	updated_date timestamp NULL,
	CONSTRAINT company_tax_addresses_pk PRIMARY KEY (id)
);


-- public.customer_tax_addresses definition

-- Drop table

-- DROP TABLE public.customer_tax_addresses;

CREATE TABLE public.customer_tax_addresses (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	company int4 NOT NULL,
	country int4 NOT NULL,
	province_state int4 NOT NULL,
	zip_code varchar(15) NOT NULL,
	city varchar(50) NOT NULL,
	street varchar(100) NOT NULL,
	"number" varchar(10) NULL,
	created_date timestamp NOT NULL DEFAULT now(),
	created_user varchar(10) NOT NULL,
	updated_date timestamp NULL,
	updated_user varchar(10) NULL,
	CONSTRAINT customer_tax_addresses_pk PRIMARY KEY (id)
);


-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	role_type varchar(10) NOT NULL,
	description varchar(10) NOT NULL,
	description_key varchar(50) NOT NULL,
	CONSTRAINT roles_pk PRIMARY KEY (id)
);


-- public.companies definition

-- Drop table

-- DROP TABLE public.companies;

CREATE TABLE public.companies (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(40) NOT NULL,
	principal_brand_logo bytea NULL,
	primary_brand_color varchar(7) NULL,
	secundary_brand_color varchar(7) NULL,
	tax_address int4 NULL,
	created_user varchar(8) NOT NULL,
	created_date timestamp NOT NULL DEFAULT now(),
	updated_user varchar(8) NULL,
	updated_date timestamp NULL,
	currency varchar(3) NOT NULL DEFAULT 'EUR'::character varying,
	CONSTRAINT companies_pk PRIMARY KEY (id),
	CONSTRAINT companies_fk FOREIGN KEY (id) REFERENCES public.company_tax_addresses(id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(15) NOT NULL,
	surname varchar(30) NOT NULL,
	email varchar(50) NOT NULL,
	"password" varchar(100) NULL,
	active bool NOT NULL DEFAULT false,
	"locked" bool NOT NULL DEFAULT false,
	"role" int4 NOT NULL,
	created_date timestamp NOT NULL DEFAULT now(),
	code varchar(10) NOT NULL,
	failed_attemps int4 NOT NULL DEFAULT 0,
	owner_company int4 NOT NULL DEFAULT '-1'::integer,
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT fk_user_role FOREIGN KEY ("role") REFERENCES public.roles(id)
);
